// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEFEqc1GrpDKSx0HVuNdiaJeU2NdQbyao',
    appId: '1:89186751432:web:0e5973e5624d599cac26fd',
    messagingSenderId: '89186751432',
    projectId: 'sampleproj-35ee3',
    authDomain: 'sampleproj-35ee3.firebaseapp.com',
    databaseURL: 'https://sampleproj-35ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sampleproj-35ee3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3bu7HOdEAfbhRuJ9W2ul0abI_kMyt8QI',
    appId: '1:89186751432:android:59c3ee3d1654970aac26fd',
    messagingSenderId: '89186751432',
    projectId: 'sampleproj-35ee3',
    databaseURL: 'https://sampleproj-35ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sampleproj-35ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpR-qkkvSUeKfz_K6-os_mWYv88HSWFzY',
    appId: '1:89186751432:ios:0e5afb21f5b1be24ac26fd',
    messagingSenderId: '89186751432',
    projectId: 'sampleproj-35ee3',
    databaseURL: 'https://sampleproj-35ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sampleproj-35ee3.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpR-qkkvSUeKfz_K6-os_mWYv88HSWFzY',
    appId: '1:89186751432:ios:0e5afb21f5b1be24ac26fd',
    messagingSenderId: '89186751432',
    projectId: 'sampleproj-35ee3',
    databaseURL: 'https://sampleproj-35ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sampleproj-35ee3.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEFEqc1GrpDKSx0HVuNdiaJeU2NdQbyao',
    appId: '1:89186751432:web:2f2afd80163b5741ac26fd',
    messagingSenderId: '89186751432',
    projectId: 'sampleproj-35ee3',
    authDomain: 'sampleproj-35ee3.firebaseapp.com',
    databaseURL: 'https://sampleproj-35ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sampleproj-35ee3.firebasestorage.app',
  );

}